# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rwright <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/24 20:00:48 by rwright           #+#    #+#              #
#    Updated: 2019/01/24 20:00:49 by rwright          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@gcc -Wall -Werror -Wextra *.c -c
	@gcc *.o -o ft_display_file

clean:
	@rm -f *.o

fclean: clean
	@rm -f ft_display_file
